version: '3'
services:
  my-mongodb:
    image: mongo:4.2.6
    container_name: my-mongodb
    restart: always
    networks:
      - my_net
    ports:
      - 27017:27017
    env_file: .env
    volumes:
# 数据卷，如需持久化，打开下方注解。windows,由于mongodb的文件结构存在冲突，无法使用。
#      - ./data:/data/db
      - ./script/:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: my_test
# 通过命令行的方式开启认证
#    command:
#      - auth

networks:
  my_net:
    external: false