version: '3'
services:
  middle-dict-mongo:
    image: docker.nb.bluetron.cn/bluetron/mongo:4.2.6
    container_name: middle-dict-mongo
    restart: always
    networks:
      - middle-dict-net
    ports:
      - 27017:27017
    env_file: .env
    volumes:
      - ./data:/data/db
      - ./script/:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_DATABASE: my_test

networks:
  middle-dict-net:
    external: false