version: '3'
services:
  my-mongodb:
    image: mongo:4.2.6
    container_name: my-mongodb
    restart: always
    networks:
      - my_net
    ports:
      - 27017:27017
    env_file: .env
    volumes:
      - ./data:/data/db
      - ./script/:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: my_test

networks:
  my_net:
    external: false